// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1NY6645HdojezKgH_GrSzTYuvjBWafww',
    appId: '1:545902211367:web:c4235139b21503ff847902',
    messagingSenderId: '545902211367',
    projectId: 'massanger-6f8bb',
    authDomain: 'massanger-6f8bb.firebaseapp.com',
    storageBucket: 'massanger-6f8bb.appspot.com',
    measurementId: 'G-8SD713JNNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnF6cY0cUzvBw-M0zGOC3wTDmtwumfNRw',
    appId: '1:545902211367:android:5bff09d931f30f30847902',
    messagingSenderId: '545902211367',
    projectId: 'massanger-6f8bb',
    storageBucket: 'massanger-6f8bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZNY0eEuPb6RBJ7Po8KgfPagSA7z5Pdt8',
    appId: '1:545902211367:ios:d947e2f40b56f208847902',
    messagingSenderId: '545902211367',
    projectId: 'massanger-6f8bb',
    storageBucket: 'massanger-6f8bb.appspot.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZNY0eEuPb6RBJ7Po8KgfPagSA7z5Pdt8',
    appId: '1:545902211367:ios:d947e2f40b56f208847902',
    messagingSenderId: '545902211367',
    projectId: 'massanger-6f8bb',
    storageBucket: 'massanger-6f8bb.appspot.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1NY6645HdojezKgH_GrSzTYuvjBWafww',
    appId: '1:545902211367:web:07e6b968a17a6ec9847902',
    messagingSenderId: '545902211367',
    projectId: 'massanger-6f8bb',
    authDomain: 'massanger-6f8bb.firebaseapp.com',
    storageBucket: 'massanger-6f8bb.appspot.com',
    measurementId: 'G-8N3S55X532',
  );
}
